-- 027: Remove seed fixture jobs and one unprotected invalid row
--
-- WHAT THIS DELETES
-- Exactly 26 rows, named individually:
--   * the 25 fixture jobs inserted by migration 008 ("JOBS (25 realistic
--     jobs)"), ids b0000000-...-000000000001 through ...025. Their URLs
--     (sf-dev-001, react-dev-001, be-eng-001, ...) were never real postings.
--   * f379016f-2c06-4677-8daa-3110534179cc — "Unknown Title / Unknown Company",
--     an empty extraction from jobs.lever.co with no description.
--
-- WHY AN EXPLICIT ID LIST
-- No predicate is used. Not `score < 30`, not a title or company LIKE, not an
-- id prefix. A predicate would silently widen as data changes; this list is
-- auditable and cannot match a row nobody reviewed. If an id has already been
-- removed the statement simply matches nothing.
--
-- THE SCORE RULE DOES NOT APPLY HERE
-- Dummy data is removed because it is dummy, independently of its score. Two of
-- these fixtures matter for that distinction:
--   b0000000-...-000000000003  GitLab            27.00  (below 30)
--   b0000000-...-000000000015  Vercel            30.00  (exactly 30)
-- A REAL job scoring exactly 30 would be kept, and at the time of writing no
-- real job scores below 30 and no job is unscored. Both of these go only
-- because they are fixtures.
--
-- WHAT IS DELIBERATELY NOT DELETED
-- 2bc5ead5-3654-4dc6-b2dd-2c5106ace701 is also "Unknown Title / Unknown
-- Company" and is equally junk, but it carries one application and one
-- application_event. Every foreign key into jobs is ON DELETE CASCADE, and
-- application_events cascades from applications, so removing the job would
-- destroy real application history. Junk with history is kept.
--
-- CASCADE FOOTPRINT (verified before writing this migration)
-- The 26 rows carry 26 job_matches, 11 job_source_mappings, 26 job_locations
-- and 56 job_skills. All are derived data, regenerated by discovery and
-- matching. They carry ZERO applications, ZERO application_events and ZERO
-- saved_jobs — checked explicitly, and the guard below re-checks it at apply
-- time rather than trusting that snapshot.
--
-- crawl_runs is unaffected: it has no foreign key to jobs.

BEGIN;

CREATE TEMP TABLE _doomed_jobs (id UUID PRIMARY KEY) ON COMMIT DROP;

INSERT INTO _doomed_jobs (id) VALUES
  -- 25 seed fixtures from migration 008
  ('b0000000-0000-0000-0000-000000000001'), -- Infosys, Senior Salesforce Developer
  ('b0000000-0000-0000-0000-000000000002'), -- Deloitte, Salesforce Technical Architect
  ('b0000000-0000-0000-0000-000000000003'), -- GitLab, Senior Full Stack Engineer (27.00)
  ('b0000000-0000-0000-0000-000000000004'), -- TCS, React.js Developer
  ('b0000000-0000-0000-0000-000000000005'), -- Wipro, Senior Cloud Engineer (AWS)
  ('b0000000-0000-0000-0000-000000000006'), -- Stripe, Backend Engineer - Payments
  ('b0000000-0000-0000-0000-000000000007'), -- Flipkart, DevOps Engineer
  ('b0000000-0000-0000-0000-000000000008'), -- Spotify, Senior Data Engineer
  ('b0000000-0000-0000-0000-000000000009'), -- Cognizant, Salesforce Administrator
  ('b0000000-0000-0000-0000-000000000010'), -- Razorpay, Senior Product Manager - Payments
  ('b0000000-0000-0000-0000-000000000011'), -- Datadog, Site Reliability Engineer
  ('b0000000-0000-0000-0000-000000000012'), -- Freshworks, Node.js Backend Developer
  ('b0000000-0000-0000-0000-000000000013'), -- Google, Machine Learning Engineer
  ('b0000000-0000-0000-0000-000000000014'), -- Accenture, Salesforce Commerce Cloud Developer
  ('b0000000-0000-0000-0000-000000000015'), -- Vercel, Frontend Engineer (exactly 30.00)
  ('b0000000-0000-0000-0000-000000000016'), -- Persistent, Salesforce Integration Developer
  ('b0000000-0000-0000-0000-000000000017'), -- Zoho, Senior Python Developer
  ('b0000000-0000-0000-0000-000000000018'), -- Microsoft, Technical Lead - Azure
  ('b0000000-0000-0000-0000-000000000019'), -- HCLTech, QA Automation Engineer
  ('b0000000-0000-0000-0000-000000000020'), -- AWS, Solutions Architect
  ('b0000000-0000-0000-0000-000000000021'), -- Capgemini, Salesforce CPQ Specialist
  ('b0000000-0000-0000-0000-000000000022'), -- GitHub, Senior Mobile Engineer (React Native)
  ('b0000000-0000-0000-0000-000000000023'), -- Tech Mahindra, Lightning Web Components Developer
  ('b0000000-0000-0000-0000-000000000024'), -- Shopify, Senior Platform Engineer
  ('b0000000-0000-0000-0000-000000000025'), -- IBM, Salesforce Marketing Cloud Developer
  -- Unprotected legacy junk: empty extraction, no application history
  ('f379016f-2c06-4677-8daa-3110534179cc');

-- Guard 1: never delete a job carrying user history. This is the same check
-- performed during the audit, repeated here so the migration is safe on its
-- own terms — if Production has changed since, this aborts instead of
-- destroying history.
DO $$
DECLARE
    protected_count INTEGER;
BEGIN
    SELECT count(*) INTO protected_count
    FROM _doomed_jobs d
    WHERE EXISTS (SELECT 1 FROM public.applications a WHERE a.job_id = d.id)
       OR EXISTS (SELECT 1 FROM public.saved_jobs s WHERE s.job_id = d.id);

    IF protected_count > 0 THEN
        RAISE EXCEPTION
            'Aborting: % of the listed jobs now carry applications or saved_jobs. Re-audit before deleting.',
            protected_count;
    END IF;
END $$;

-- Guard 2: the job deliberately retained must never appear in the list.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM _doomed_jobs WHERE id = '2bc5ead5-3654-4dc6-b2dd-2c5106ace701') THEN
        RAISE EXCEPTION 'Aborting: the protected job 2bc5ead5 is in the deletion list.';
    END IF;
END $$;

DELETE FROM public.jobs j USING _doomed_jobs d WHERE j.id = d.id;

COMMIT;

COMMENT ON TABLE public.jobs IS
  'Discovered job postings. Migration 027 removed the 25 seed fixtures from migration 008 and one empty extraction; one equally invalid row was retained because it carries application history.';
